Repository google/tour-of-wgsl, pull requests merged in 2023-04, with the labels that each got.

#1 Change inner html into a pre.
  layouts/_default/baseof.html
Labels: bug

#2 Update buttons to use arrows.
  layouts/_default/baseof.html
Labels: enhancement

#4 Show more helpful error when WebGPU is unsupported
  assets/ts/wgsl-tour.ts
Labels: bug

#7 Update Hugo baseURL
  assets/sass/style.scss
  config.toml
  layouts/partials/header.html
Labels: bug

#6 Hover style for header.
  assets/sass/style.scss
Labels: enhancement

#5 Add a note on the editor features.
  content/_index.md
Labels: documentation

#3 Update URL in package.json.
  package-lock.json
  package.json
Labels: bug

#12 Add some footer links.
  assets/sass/style.scss
  layouts/partials/footer.html
Labels: enhancement

#11 Move control-flow shader.
  content/05-control-flow/_index.md
  content/05-control-flow/index.wgsl
  content/index.wgsl
Labels: enhancement

#32 Update pages to use {{< pages >}} short code
  content/05-control-flow/_index.md
  content/06-binding-points/_index.md
  content/07-uniformity-analysis/_index.md
Labels: bug

#34 Fixup internal links.
  content/01-functions/03-entry-points.md
  content/02-types/01-basic-scalars.md
  content/02-types/02-abstract-numerics.md
  content/03-expressions/01-evaluation-stage/01-constant/02-builtins.md
  content/03-expressions/01-evaluation-stage/01-constant/_index.md
  content/03-expressions/01-evaluation-stage/02-override/_index.md
  content/03-expressions/01-evaluation-stage/03-runtime/_index.md
  content/03-expressions/01-evaluation-stage/_index.md
  content/03-expressions/02-operators/_index.md
  content/04-variables/01-var-function.md
  content/04-variables/02-var-private.md
  content/04-variables/03-var-workgroup.md
  content/04-variables/07-let.md
  content/04-variables/08-const.md
  content/04-variables/10-shadowing.md
Labels: bug

#35 Add switch statement
  content/05-control-flow/2-switch-statements.md
  content/05-control-flow/switch.wgsl
Labels: enhancement

#41 Update URL in README.md file.
  README.md
Labels: enhancement

#42 Add `for` statement page.
  content/05-control-flow/3-for-statements.md
  content/05-control-flow/for.wgsl
Labels: documentation

#48 Mark stub pages.
  content/binding-points/attributes.md
  content/binding-points/storage-buffers.md
  content/binding-points/textures.md
  content/binding-points/uniform-buffers.md
  content/control-flow/loop-statements.md
  content/control-flow/while-statements.md
  content/types/arrays.md
  content/types/atomics.md
  content/types/pointers.md
  content/types/structures.md
  content/uniformity-analysis/fragment-derivative-builtins.md
  content/uniformity-analysis/invocations.md
  content/variables/override.md
  content/variables/var-handle.md
  content/variables/var-storage.md
  content/variables/var-uniform.md
Labels: bug

#39 Add mermaid diagram support
  assets/ts/app.ts
  layouts/_default/_markup/render-codeblock-mermaid.html
  layouts/_default/baseof.html
  layouts/partials/mermaid.html
  package-lock.json
  package.json
Labels: enhancement

#44 Overview evaluation phases
  assets/sass/style.scss
  content/expressions/evaluation-stage/_index.md
  content/expressions/evaluation-stage/overview/_index.md
  data/PageOrder.json
Labels: enhancement

#51 Update execution overview styling.
  content/expressions/evaluation-stage/overview/_index.md
Labels: enhancement

#65 Make footer vertical when screen is small.
  assets/sass/style.scss
  layouts/partials/footer.html
Labels: enhancement

#71 const-declarations are for const-expressions
  content/variables/const.md
Labels: bug

#70 Add a `warning` class.
  assets/sass/style.scss
  content/types/atomics.md
  content/types/atomics/_index.md
  layouts/partials/head.html
  static/third_party/icons/material/warning.svg
Labels: enhancement

#78 Update size of warning icon.
  assets/sass/style.scss
Labels: enhancement
